---
title: "Task2"
output: html_document
date: "2023-04-15"
---

## Load necessary libraries

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library(caret)
library(randomForest)
library(e1071)
library(ggplot2)
library(kernlab)
library(ISLR)
library(dplyr)
library(nnet)
```

```{r}
train_data <- read.table("~/Desktop/bios626-mid1/bios626-main/data/training_data.txt", header=TRUE, quote="", comment.char="")
test_data <- read.table("~/Desktop/bios626-mid1/bios626-main/data/test_data.txt", header=TRUE, quote="", comment.char="", stringsAsFactors=TRUE)
```

```{r}
train_data$activity <- as.factor(ifelse(train_data$activity >= 7, 7, train_data$activity)) 
head(train_data)
```

```{r}
# Split the data into features and labels
train_features <- train_data[, -(1:2)] # features from F1 to F561 from training_set
train_labels <- train_data$activity
test_features <- test_data[, -(1)] # features from F1 to F561 from testing_set

# in order to test the accuracy of different method
true_data <- sample_n(train_data, 0.2*7767)
true_labels <- true_data$activity
true_features <- true_data[, -(1:2)]
dim(true_features)

left_data <- setdiff(train_data, true_data)
left_labels <- left_data$activity
left_features <- left_data[, -(1:2)]
dim(left_data)
```

## Fit svm

```{r}
set.seed(123)
classifer <- svm( y = left_labels, x = left_features, kernel = "radial", probability = T)
predictions.svm <- predict(classifer, true_features)
accuracy <- sum(predictions.svm == true_labels)/ length(true_labels)
print(accuracy)
```

## Train random forest

```{r}
# train random forest
set.seed(123)
model1 <- randomForest(x = left_features, y = left_labels, ntree = 500, importance = TRUE)

# Make predictions on the test dataset
predictions <- predict(model1, true_features)
head(predictions)

# Evaluate the model's accuracy
accuracy <- sum(predictions == true_labels) / length(true_labels)
cat("Accuracy on test dataset:", accuracy * 100, "%\n")

```

## Produce the results on the test_data

```{r}
model <- randomForest(x = train_features, y = train_labels, ntree = 500, importance = TRUE)
result <- predict(model,test_features)
head(result)

```

```{r}
write.table(result, "multiclass_2502.txt",row.names = F, col.names = F, quote = F)
```
